// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaFPvs1ZSE5vAHz2PfLQu2MBqVK4aKnrw',
    appId: '1:1042233465664:web:287fc072007c11713678a5',
    messagingSenderId: '1042233465664',
    projectId: 'touristop-dev',
    authDomain: 'touristop-dev.firebaseapp.com',
    storageBucket: 'touristop-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBcFzyXXQ5VYNpFqXBbzPWjwRGQErqjo',
    appId: '1:1042233465664:android:d579189205f6bd8a3678a5',
    messagingSenderId: '1042233465664',
    projectId: 'touristop-dev',
    storageBucket: 'touristop-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1EiY61g_IVDlC2LT99GbTTV73TdHR7s',
    appId: '1:1042233465664:ios:de40a56a2b4019063678a5',
    messagingSenderId: '1042233465664',
    projectId: 'touristop-dev',
    storageBucket: 'touristop-dev.appspot.com',
    iosClientId:
        '1042233465664-19ofjh0qk572trd7ki1oql0os35d5170.apps.googleusercontent.com',
    iosBundleId: 'com.example.touristop',
  );
}
